[project]
name = "ai-pdf-parser-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ollama>=0.6.1",
    "pymupdf>=1.26.5",
    "requests>=2.32.5",
]
